apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: inspectr
  namespace: inspectr
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        kubernetes.io/hostname: inspectr
      labels:
        app: inspectr
    spec:
      serviceAccountName: inspectr-serviceaccount
      containers:
      - name: inspectr
        image: eversc/inspectr
        imagePullPolicy: Always
        resources:
          requests:
            memory: 50Mi
            cpu: 50m
          limits:
            memory: 100Mi
            cpu: 100m
        env:
          - name: INSPECTR_SLACK_WEBHOOK_ID
            valueFrom:
              secretKeyRef:
                name: inspectr-secret
                key: webhookID
          - name: INSPECTR_JIRA_URL
            valueFrom:
              secretKeyRef:
                name: inspectr-url-secret
                key: jiraURL
          - name: INSPECTR_JIRA_PARAMS
            valueFrom:
              secretKeyRef:
                name: inspectr-param-secret
                key: jiraParams
